spring.application.name=bankapp
server.port=8081

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://nagendravernekar06_db_user:Nagendra12345@cluster0.ntvjlbc.mongodb.net/bankapp?retryWrites=true&w=majority&appName=Cluster0

# Thymeleaf
spring.thymeleaf.cache=false
