spring.application.name=bankapp
server.port=8081

# MongoDB Atlas
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Thymeleaf
spring.thymeleaf.cache=false

# Actuator - Prometheus Monitoring
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
