apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: nagendra06/bankapp:69778a659012785bc37afa17ecda31315c659182
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb+srv://nagendravernekar06_db_user:Nagendra12345@cluster0.ntvjlbc.mongodb.net/bankapp?retryWrites=true&w=majority&appName=Cluster0"
