name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build project (H2 in-memory, no MySQL needed)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Login to DockerHub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Build Docker image
      - name: Build Docker Image
        run: docker build -t nagendra06/bankapp:${{ github.sha }} .

      # 6. Push Docker image
      - name: Push Docker Image
        run: docker push nagendra06/bankapp:${{ github.sha }}

      # 7. Update deployment.yaml with new image
      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: nagendra06/bankapp:.*|image: nagendra06/bankapp:${{ github.sha }}|" k8s/deployment.yaml

      # 8. Commit & push updated YAML
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
          git push
